.PHONY: all help clean push test build lock

export VERSION = 1.0.7
export AWS_DEFAULT_REGION = us-east-1

RUBY_VERSION := 4.0.5

DOCKER_RUN := docker run \
	--rm \
	--workdir=/app \
	-v `pwd`:/app \
	-e VERSION

RUBY_IMAGE := ruby:$(RUBY_VERSION)

build: ## Create the docker image.
	@echo "--- :wind_chime: Building :wind_chime:"
	$(DOCKER_RUN) \
		$(RUBY_IMAGE) \
		gem build fluent-plugin-annotation-filter.gemspec

test: ## Run the app tests.
	@echo "--- :fire: Testing :fire:"
	$(DOCKER_RUN) \
		-e BUNDLE_PATH=/app/gems \
		$(RUBY_IMAGE) \
		script/docker-rspec.sh

lock: ## Re-resolve all dependencies and recreate Gemfile.lock.
	@echo "--- :lock: Locking dependencies :lock:"
	$(DOCKER_RUN) \
		-e BUNDLE_PATH=/app/gems \
		-e BUNDLE_VERSION=system \
		$(RUBY_IMAGE) \
		bundle lock --update

push: build ## Publish the gem
	$(if $(RUBY_GEMS_API_KEY),,$(error RUBY_GEMS_API_KEY is not set))
	$(if $(RUBY_GEMS_OTP),,$(error RUBY_GEMS_OTP is not set))
	@echo "--- :fire: Pushing! :fire:"
	$(DOCKER_RUN) \
		-e BUNDLE_PATH=/app/gems \
		-e RUBY_GEMS_API_KEY \
		-e RUBY_GEMS_OTP \
		-it \
		$(RUBY_IMAGE) \
		script/push-gem.sh

clean: ## Cleanup artifacts generated by build.
	@echo "--- :shower: Cleaning up :shower:"
	-rm *.gem

all: build test push
