.PHONY: all help clean push test build

RUBY_IMAGE := ruby:3.4.8-trixie
export VERSION = 1.1.0

define AWS
    docker container run --rm -i \
	  -e AWS_PROFILE \
	  -v "${HOME}/.aws:/root/.aws:ro" \
      amazon/aws-cli:latest
endef

build: ## Create the docker image.
	@echo "--- :wind_chime: Building :wind_chime:"
	docker run \
		--rm \
		--workdir=/app \
		-v `pwd`:/app \
		-e VERSION \
		${RUBY_IMAGE} \
		gem build fluent-plugin-annotation-filter.gemspec

test: ## Run the app tests.
	@echo "--- :fire: Testing :fire:"
	docker run \
		--rm \
		--workdir=/app \
		-v `pwd`:/app \
		-e VERSION \
		-e BUNDLE_PATH=/app/gems \
		${RUBY_IMAGE} \
		script/docker-rspec.sh

push: GEM_HOST_API_KEY = $(shell $(AWS) secretsmanager get-secret-value --secret-id rubygems_api_key --output json | jq -r '.SecretString | fromjson | .rubygems_api_key')
push: build ## Publish the gem
	@echo "--- :fire: Pushing! :fire:"
	docker run \
		--rm \
		--workdir=/app \
		-v `pwd`:/app \
		-e VERSION \
		-e BUNDLE_PATH=/app/gems \
		-e GEM_HOST_API_KEY=$(GEM_HOST_API_KEY) \
		-it \
		${RUBY_IMAGE} \
		script/push-gem.sh

clean: ## Cleanup artifacts generated by build.
	@echo "--- :shower: Cleaning up :shower:"
	-rm *.gem

all: build test push
